ALL: ex1 ex71

CFLAGS      = -I.
FFLAGS      =
CPPFLAGS    =
FPPFLAGS    =
LOCDIR      = src/tutorials/feti
EXAMPLESC   = ex1.c ex71.c
EXAMPLECH   =
EXAMPLESF   =
MANSEC      =

include ${PERMON_DIR}/lib/permon/conf/permon_base
include ${PERMON_DIR}/lib/permon/conf/permon_test

