ALL: ex1 ex71

CFLAGS      = -I.
FFLAGS      =
CPPFLAGS    =
FPPFLAGS    =
TUTORIALS   = ex1.c ex71.c
EXAMPLESC   = ex1.c ex71.c
EXAMPLECH   =
EXAMPLESF   =
EXAMPLESFH  =
LOCDIR      = src/examples/feti
MANSEC      =
DOCS        =
DIRS        =
CLEANFILES  = ex1 ex71

include ${PERMON_DIR}/lib/permon/conf/permon_base
include ${PERMON_DIR}/lib/permon/conf/permon_test

