ALL: ex1 ex2 ex3 ex4 ex5

CFLAGS      =
FFLAGS      =
CPPFLAGS    =
FPPFLAGS    =
LOCDIR      = src/tests
EXAMPLESC   = ex1.c ex2.c ex3.c ex4.c ex5.c
EXAMPLESF   =
MANSEC      =
CLEANFILES  =

include ${PERMON_DIR}/lib/permon/conf/permon_base
include ${PERMON_DIR}/lib/permon/conf/permon_test

