ALL: ex1 ex2

CFLAGS      =
FFLAGS      =
CPPFLAGS    =
FPPFLAGS    =
LOCDIR      = src/tests
EXAMPLESC   = ex1.c ex2.c
EXAMPLESF   =
MANSEC      =
CLEANFILES  =

include ${PERMON_DIR}/lib/permon/conf/permon_base
include ${PERMON_DIR}/lib/permon/conf/permon_test

