
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = matblockdiag.c
SOURCEF  =
SOURCEH  =
OBJSC    = ${SOURCEC:.c=.o}
OBJSF    =
LIBBASE  = libpermon
MANSEC   = Mat
LOCDIR   = src/mat/impls/blockdiag/

include ${PERMON_DIR}/lib/permon/conf/permon_base
