
ALL: lib 

CFLAGS   =
FFLAGS   =
SOURCEC  = dcg.c dcgspaces.c
SOURCEF  =
SOURCEH  =
OBJSC    = ${SOURCEC:.c=.o}
OBJSF    =
LIBBASE  = libpermon
MANSEC   = DCG
LOCDIR   = src/ksp/impls/dcg

include ${PERMON_DIR}/lib/permon/conf/permon_base
