
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = fllopvecutils.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = ${SOURCEC:.c=.o}
OBJSF    = 
LIBBASE  = libpermon
MANSEC   = Vec
LOCDIR   = src/vec/interface/

include ${PERMON_DIR}/lib/permon/conf/permon_base
