
ALL: lib 

CFLAGS   =
FFLAGS   =
SOURCEC  = pcpg.c
SOURCEF  =
SOURCEH  = pcpgimpl.h
OBJSC    = ${SOURCEC:.c=.o}
OBJSF    =
LIBBASE  = libpermon
MANSEC   = QPS
LOCDIR   = src/qps/impls/PCPG/

include ${PERMON_DIR}/lib/permon/conf/permon_base
