
ALL: lib 

CFLAGS   =
FFLAGS   =
SOURCEC  = qpstao.c
SOURCEF  =
SOURCEH  = qpstaoimpl.h
OBJSC    = ${SOURCEC:.c=.o}
OBJSF    =
LIBBASE  = libpermon
MANSEC   = QPS
LOCDIR   = src/qps/impls/tao/

include ${PERMON_DIR}/lib/permon/conf/permon_base
