
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = qpc.c qpcreg.c dlregisqpc.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = ${SOURCEC:.c=.o} 
LIBBASE  = libpermon
DIRS     =
MANSEC   = QPC
LOCDIR   = src/qpc/interface/

include ${PERMON_DIR}/lib/permon/conf/permon_base
