
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = permoninit.c petscretro.c utils.c
SOURCEF  =
SOURCEH  = ../../include/permonpetscretro.h
OBJSC    = ${SOURCEC:.c=.o}
LIBBASE  = libpermon
DIRS     =
MANSEC   = Sys
LOCDIR   = src/sys/

include ${PERMON_DIR}/lib/permon/conf/permon_base
