
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = fllopinit.c petscretro.c utils.c
SOURCEF  = 
SOURCEH  = ../../include/flloputils.h ../../include/flloppetscretro.h
OBJSC    = ${SOURCEC:.c=.o}
LIBBASE  = libpermon
DIRS     =
MANSEC   = sys
LOCDIR   = src/sys

include ${PERMON_DIR}/lib/permon/conf/permon_base
