
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = aif.c
SOURCEF  = 
SOURCEH  = ../../include/permonaif.h
OBJSC    = ${SOURCEC:.c=.o}
LIBBASE  = libpermon
DIRS     =
MANSEC   = AIF
LOCDIR   = src/interface/

include ${PERMON_DIR}/lib/permon/conf/permon_base
