
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = qp.c qpchain.c qptransform.c dlregisqp.c
SOURCEF  =
SOURCEH  =
OBJSC    = ${SOURCEC:.c=.o}
LIBBASE  = libpermon
DIRS     =
MANSEC   = QP
LOCDIR   = src/qp/interface/

include ${PERMON_DIR}/lib/permon/conf/permon_base
