
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = qpsksp.c
SOURCEF  =
SOURCEH  = qpskspimpl.h
OBJSC    = ${SOURCEC:.c=.o}
OBJSF    =
LIBBASE  = libpermon
MANSEC   = QPS
LOCDIR   = src/qps/impls/ksp/

include ${PERMON_DIR}/lib/permon/conf/permon_base
