
ALL: lib

SOURCEH  = ../../include/permon/private/fllopmatimpl.h ../../include/fllopmat.h
DIRS     = interface impls
LOCDIR   = src/mat/
MANSEC   = Mat

include ${PERMON_DIR}/lib/permon/conf/permon_base
