ALL: ex1

CFLAGS      = -I.
FFLAGS      =
CPPFLAGS    =
FPPFLAGS    =
TUTORIALS   = ex1.c ex2.c jbearing2.c
EXAMPLESC   = ex1.c ex2.c jbearing2.c
EXAMPLECH   =
EXAMPLESF   =
EXAMPLESFH  =
LOCDIR      = src/examples
MANSEC      =
DOCS        =
DIRS        =
CLEANFILES  = ex1 ex2 jbearing2

include ${PERMON_DIR}/lib/permon/conf/permon_base
include ${PERMON_DIR}/lib/permon/conf/permon_test

