ALL: ex1 ex2 ex3 ex4 jbearing2

CFLAGS      = -I.
FFLAGS      =
CPPFLAGS    =
FPPFLAGS    =
LOCDIR      = src/tutorials
EXAMPLESC   = ex1.c ex2.c ex3.c ex4.c jbearing2.c
EXAMPLESF   =
MANSEC      = QP
CLEANFILES  = jbearing2

include ${PERMON_DIR}/lib/permon/conf/permon_base
include ${PERMON_DIR}/lib/permon/conf/permon_test

