
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = qppf.c dlregisqppf.c
SOURCEF  =
SOURCEH  =
OBJSC    = ${SOURCEC:.c=.o}
LIBBASE  = libpermon
DIRS     =
MANSEC   = QPPF
LOCDIR   = src/qppf/interface/

include ${PERMON_DIR}/lib/permon/conf/permon_base
