
ALL: lib 

CFLAGS   =
FFLAGS   =
SOURCEC  = feti.c
SOURCEF  =
SOURCEH  =
OBJSC    = ${SOURCEC:.c=.o}
OBJSF    =
LIBBASE  = libpermon
LOCDIR   = src/ksp/impls/feti/

include ${PERMON_DIR}/lib/permon/conf/permon_base
