
ALL: lib 

CFLAGS   =
FFLAGS   =
SOURCEC  = dense.c nest.c normm.c sbaij.c shell.c transm.c
SOURCEF  =
SOURCEH  = 
OBJSC    = ${SOURCEC:.c=.o}
OBJSF    =
LIBBASE  = libpermon
MANSEC   = Mat
LOCDIR   = src/mat/impls/petscfix/

include ${PERMON_DIR}/lib/permon/conf/permon_base
