
ALL: lib 

CFLAGS   =
FFLAGS   =
SOURCEC  = matsum.c matprod.c
SOURCEF  =
SOURCEH  = fllopcompositemimpl.h
OBJSC    = ${SOURCEC:.c=.o}
OBJSF    =
LIBBASE  = libpermon
MANSEC   = Mat
LOCDIR   = src/mat/impls/composite/

include ${PERMON_DIR}/lib/permon/conf/permon_base
