
ALL: lib 

CFLAGS   =
FFLAGS   =
SOURCEC  = permonmatfetiutils.c
SOURCEF  =
SOURCEH  = 
OBJSC    = ${SOURCEC:.c=.o}
OBJSF    =
LIBBASE  = libpermon
MANSEC   = Mat
LOCDIR   = src/mat/utils/

include ${PERMON_DIR}/lib/permon/conf/permon_base
