
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = permonmatregis.c permonmatutils.c permonmatregularize.c permonmatcomplete.c permonmatmatmult.c permonmatorth.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = ${SOURCEC:.c=.o}
OBJSF    = 
LIBBASE  = libpermon
MANSEC   = Mat
LOCDIR   = src/mat/interface/

include ${PERMON_DIR}/lib/permon/conf/permon_base
