
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = fllopmatregis.c fllopmatutils.c fllopmatregularize.c fllopmatcomplete.c fllopmatmatmult.c fllopmatorth.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = ${SOURCEC:.c=.o}
OBJSF    = 
LIBBASE  = libpermon
MANSEC   = Mat
LOCDIR   = src/mat/interface/

include ${PERMON_DIR}/lib/permon/conf/permon_base
