
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = permonpcregis.c
SOURCEF  =
SOURCEH  =
OBJSC    = ${SOURCEC:.c=.o}
OBJSF    =
LIBBASE  = libpermon
MANSEC   = PC
LOCDIR   = src/pc/interface/

include ${PERMON_DIR}/lib/permon/conf/permon_base
