
ALL: lib 

CFLAGS   =
FFLAGS   =
SOURCEC  = smalxe.c
SOURCEF  =
SOURCEH  = smalxeimpl.h
OBJSC    = ${SOURCEC:.c=.o}
OBJSF    =
LIBBASE  = libpermon
DIRS     =
MANSEC   = SMALXE
LOCDIR   = src/qps/impls/smalxe/

include ${PERMON_DIR}/lib/permon/conf/permon_base
