
ALL: lib

SOURCEH  = ../../include/permon/private/qpcimpl.h ../../include/permonqpc.h
DIRS     = interface impls
LOCDIR   = src/qpc/
MANSEC   = QPC

include ${PERMON_DIR}/lib/permon/conf/permon_base
