
ALL: lib 

CFLAGS   =
FFLAGS   =
SOURCEC  = gp.c
SOURCEF  =
SOURCEH  = gpimpl.h
OBJSC    = ${SOURCEC:.c=.o}
OBJSF    =
LIBBASE  = libpermon
MANSEC   = QPS
LOCDIR   = src/qps/impls/gp/

include ${PERMON_DIR}/lib/permon/conf/permon_base
