
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = mpgp.c
SOURCEF  =
SOURCEH  = mpgpimpl.h
OBJSC    = ${SOURCEC:.c=.o}
OBJSF    =
LIBBASE  = libpermon
MANSEC   = QPS
LOCDIR   = src/qps/impls/mpgp/

include ${PERMON_DIR}/lib/permon/conf/permon_base
