
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = qps.c qpsregis.c dlregisqps.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = ${SOURCEC:.c=.o} 
LIBBASE  = libpermon
DIRS     =
MANSEC   = QPS
LOCDIR   = src/qps/interface/

include ${PERMON_DIR}/lib/permon/conf/permon_base
