
ALL: lib 

CFLAGS     =
FFLAGS     =
SOURCEC    = qpfeti.c qpfetidirichlet.c
SOURCECXX  =
SOURCEF  	 =
SOURCEH  	 = qpfetiimpl.h
LIBBASE  	 = libpermon
MANSEC   	 = QP
LOCDIR   	 = src/qp/impls/feti/

include ${PERMON_DIR}/lib/permon/conf/permon_base

