
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = pcfreeset.c
SOURCEF  =
SOURCEH  =
OBJSC    = ${SOURCEC:.c=.o}
OBJSF    =
LIBBASE  = libpermon
MANSEC   = PC
LOCDIR   = src/pc/impls/freeset/

include ${PERMON_DIR}/lib/permon/conf/permon_base
