
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = qpcbox.c
SOURCEF  =
SOURCEH  = qpcboximpl.h
OBJSC    = ${SOURCEC:.c=.o}
OBJSF    =
LIBBASE  = libpermon
MANSEC   = QPC
LOCDIR   = src/qpc/impls/box/

include ${PERMON_DIR}/lib/permon/conf/permon_base

