
ALL: lib

SOURCEH  = ../../include/permon/private/qpimpl.h ../../include/permonqp.h
DIRS     = impls interface utils
LOCDIR   = src/qp/
MANSEC   = QP

include ${PERMON_DIR}/lib/permon/conf/permon_base
