
ALL: lib

SOURCEH  = ../../include/permon/private/qpimpl.h ../../include/permonqp.h ../../include/permonqpfeti.h
DIRS     = interface impls utils
LOCDIR   = src/qp/
MANSEC   = QP

include ${PERMON_DIR}/lib/permon/conf/permon_base
