
ALL: lib

SOURCEH  = ../../include/permon/private/qpsimpl.h ../../include/permonqps.h
DIRS     = interface impls
LOCDIR   = src/qps/
MANSEC   = QPS

include ${PERMON_DIR}/lib/permon/conf/permon_base
