
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = fllopksputils.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = ${SOURCEC:.c=.o}
OBJSF    = 
LIBBASE  = libpermon
LOCDIR   = src/ksp/interface/

include ${PERMON_DIR}/lib/permon/conf/permon_base
